-- Campus Notice Board - Supabase setup
-- Run this in the Supabase SQL Editor before testing the React app.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null,
  category text not null check (category in ('Academic', 'Event', 'Urgent', 'General')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.notices enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "notices_select_public" on public.notices;
create policy "notices_select_public"
  on public.notices for select
  using (true);

drop policy if exists "notices_insert_own" on public.notices;
create policy "notices_insert_own"
  on public.notices for insert
  with check (auth.uid() = user_id);

drop policy if exists "notices_delete_own" on public.notices;
create policy "notices_delete_own"
  on public.notices for delete
  using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'display_name', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

do $$
begin
  alter publication supabase_realtime add table public.notices;
exception
  when duplicate_object then null;
end;
$$;
